-- Basic
require('core.plugins')
require('core.mappings')
require('core.config')
require('core.colors')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.lspinstaller')
require('plugins.comments')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nullls')
require('plugins.autopairs')
require('plugins.autotag')
require('plugins.buffline')
require('plugins.dashboard')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.toggleterm')
require('plugins.whichkey')
